# Generated by Django 4.2.10 on 2024-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_shipping_pais_shippingaddress_shipping_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
