# Generated by Django 4.2.10 on 2024-04-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservadjango', '0002_categoria_servicio_imagen_alter_reserva_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
